### ISSUE TITLE
Is it Open Source?

### ISSUE THREAD

**Issue by nshiell** [TejasBhovad/ollama-ui#6]
This looks really good, I want to help improve it!
I'm not sure if the Creative Commons Licences are technically software - as they are supposed to be used for works of art not software code.

I used the GPL license in my database program https://github.com/nshiell/database-dossier/blob/master/LICENSE.md
MIT license is also very popular

https://www.ebi.ac.uk/ols4/ontologies/mcro/classes/http%253A%252F%252Fwww.ebi.ac.uk%252Fswo%252Flicense%252FSWO_1000065

P.s. I am NOT a legal expert

**Comment by TejasBhovad** [comment]
Sorry for the inconvenience, yes I meant to update the license. I updated the license to MIT and this project is Open Source. Looking forward to the improvements you could bring onto this project.

Thank you for taking the time to create this issue.
